version: "3.9"
name: webcompose-be

services:
  app:
    image: zed378/webcompose-db:latest
    container_name: webcompose_be
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./uploads:/app/uploads
      - ./log:/app/log
    environment:
      # Make sure your port same as port above
      PORT: 5000
      SECRET: 425r6@!gHT26

      # BE host and FE host
      HOST_URL: webcompose_be
      FE_URL: https://webcompose.id/login

      # DB Configuration for mysql
      DB_PORT: 3306
      DB_HOST: mysql
      DB_USER: webcompose
      DB_PASS: webcompose
      DB_NAME: webcompose
      DB_DIALECT: mysql

      # DB Configuration for postgres
      # DB_PORT: 5432
      # DB_HOST: postgresql
      # DB_USER: webcompose
      # DB_PASS: 2wsx1qaz
      # DB_NAME: webcompose
      # DB_DIALECT: postgres

      # mail setting
      # MAIL_USER: your@mail.com
      # MAIL_PASSWORD: "your_pass"
      # MAIL_HOST: host.mail.com

    depends_on:
      - mysql
      - postgresql

  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 2wsx1qaz
      POSTGRES_USER: webcompose
      POSTGRES_DB: webcompose
      PGDATA: /var/lib/postgresql/data/pgdata

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Evazed123!@#
      MYSQL_DATABASE: webcompose
      MYSQL_USER: webcompose
      MYSQL_PASSWORD: webcompose
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Evazed123!@#
      MYSQL_PASSWORD: Evazed123!@#
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Evazed123!@#
    ports:
      - 8080:80
